name: GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install
      run: npm ci
    - name: Build and Deploy
      env:
        PORT: 3000
        NODE_ENV: production
        BASE_PATH: /personal-site
        GA_ID: UA-68649021-1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
          git config user.name mldangelo
          git config user.email michael.l.dangelo@gmail.com
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/mldangelo/personal-site.git
          npm run deploy
